### ISSUE TITLE
vimE36: Not enough time

### ISSUE THREAD

**Issue by zll600** [Jint-lzxy/nvimconfig#8]
I get this error when I use nvim to edit a file. Also happens when I just use `h`, `j`, `k` , `l` to move the cursor.

![image](https://github.com/Jint-lzxy/nvimconfig/assets/71714656/7163a4e4-3b07-4be7-8e5b-46ad75de60d7)

#### neovim version

````text
nvim --version
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.1/share/nvim"

Run :checkhealth for more info
````
#### os version

````text
uname -a
Darwin myhostname 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 arm64
````
After some searching I found [this](https://www.reddit.com/r/neovim/comments/157vgt2/nvim_throwing_e36_not_enough_room_on_split) which can workaround this. Change `enable` to `false`.

https://github.com/Jint-lzxy/nvimconfig/blob/305abf14865d444f9247273483ed19ffe4d7c143/lua/modules/configs/completion/lspsaga.lua#L31

**Comment by Jint-lzxy** [comment]
Hmm I've never encountered this before. Can you provide a more detailed repro so that I can look into this issue?

**Comment by zll600** [comment]
> Hmm I've never encountered this before. Can you provide a more detailed repro so that I can look into this issue?

I just use nvim to open a file, and then move the cursor by keyboard to browse the file, and this error will be happen. Maybe something local to me is broken.

**Comment by Jint-lzxy** [comment]
> Maybe something local to me is broken.

Yeah I guess so. IMO you can open an issue in [ayamir/nvimdots](https://github.com/ayamir/nvimdots) instead b/c usually I don't guarantee that my dotfiles will work for everyone. (I do experiments from time to time and things may break w/ different environments :D)

**Comment by zll600** [comment]
Thank you for your help.
